# ######################## TRAINING ON MAMI DATASET ############

python3 src/train_multimodal_classifier.py \
--num_gcn_layers 1 \
--modality_fuser mfb \
--no_peft \
--run_name clip-vit-large_batch20_5e-6lr_1gcn_xuinit_mfb \
--logging online \
--target_column label \
--text_column text \
--image_column image_path \
--id_column file_name \
--do_train \
--do_eval \
--do_predict \
--output_dir output_mami \
--model_name_or_path openai/clip-vit-large-patch14 \
--dataset_name mami_hf_repo \
--log_level error \
--gradient_accumulation_steps 1 \
--max_seq_length 514 \
--learning_rate 5e-6 \
--num_train_epochs 10 \
--save_strategy steps \
--evaluation_strategy steps \
--fp16 \
--gradient_checkpointing \
--load_best_model_at_end \
--overwrite_cache \
--save_total_limit 1 \
--weight_decay 0.01 \
--label_smoothing_factor 0.1 \
--remove_unused_columns \
--metric_for_best_model accuracy \
--per_device_train_batch_size 20 \
--per_device_eval_batch_size 20


# ######################## TRAINING ON MEMES_EXIST 2024 DATASET ############
python3 src/train_qwen_classifier.py \
--num_gcn_layers 1 \
--no_peft \
--image_caption caption_promptA \
--run_name clip-vit-large_batch64_5e-6lr_1gcn_xuinit_mami20bs_captionPA_concat \
--logging online \
--target_column hard_label_task4 \
--text_column text_en \
--image_column image \
--id_column id \
--do_train \
--do_eval \
--do_predict \
--output_dir output_hard_label_task4 \
--checkpoint_path output_mami/clip-vit-large_batch20_5e-6lr_1gcn_xuinit_concat \
--model_name_or_path openai/clip-vit-large-patch14 \
--dataset_name exist_hf_repo \
--dataset_subset default \
--log_level error \
--gradient_accumulation_steps 1 \
--max_seq_length 514 \
--learning_rate 5e-6 \
--num_train_epochs 10 \
--save_strategy steps \
--evaluation_strategy steps \
--fp16 \
--gradient_checkpointing \
--load_best_model_at_end \
--overwrite_cache \
--save_total_limit 1 \
--weight_decay 0.01 \
--remove_unused_columns \
--metric_for_best_model loss \
--per_device_train_batch_size 64 \
--per_device_eval_batch_size 64